development:
    host: localhost
    port: 27017
    database: dentools
    logger: true

staging:
    host: localhost
    port: 27017
    database: dentools_staging
    logger: true

test:
    host: localhost
    port: 27017
    database: dentools_test
    logger: true
    
production:
    host: localhost
    port: 27017
    database: dentools
    logger: false
